export const brandMap = {
  facebook: 'facebook-f',
  twitter: 'twitter',
  instagram: 'instagram',
  linkedin: 'linkedin-in',
  youtube: 'youtube',
  github: 'github',
  tiktok: 'tiktok',
  pinterest: 'pinterest',
  reddit: 'reddit-alien',
  snapchat: 'snapchat-ghost',
  whatsapp: 'whatsapp',
  telegram: 'telegram',
  discord: 'discord',
  medium: 'medium',
  steam: 'steam',
  twitch: 'twitch',
  dribbble: 'dribbble',
  behance: 'behance'
  ,mastodon: 'mastodon'
  ,pocket: 'get-pocket'
  ,hackernews: 'hacker-news'
  ,messenger: 'facebook-messenger'
  ,tumblr: 'tumblr'
  ,skype: 'skype'
  ,viber: 'viber'
  ,line: 'line'
  ,wechat: 'weixin'
  ,sms: 'fas:sms'
}
